{% set name = "popt" %}
{% set version = "1.16" %}
{% set config_hash = "04b07fc6d9ad4fd2be7434c9ce8b03341e54ca02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: ftp://anduin.linuxfromscratch.org/BLFS/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: e728ed296fe9f069a0e005003c3d6b2dde3d9cad453422a10d6558616d304cc8
    patches:
      - 0001-remove-tests-58-and-59.patch  # [osx]
      - 0002-added-sanity-autotest.patch
      - mingw-patches/0001-nl_langinfo.mingw32.patch  # [win]
      - mingw-patches/217602.all.patch  # [win]
      - mingw-patches/318833.all.patch  # [win]
      - mingw-patches/no-uid-stuff-on.mingw32.patch  # [win]
      - mingw-patches/197416.all.patch  # [win]
      - mingw-patches/278402-manpage.all.patch  # [win]
      - mingw-patches/get-w32-console-maxcols.mingw32.patch  # [win]
  - fn: config-updated.guess
    url: http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb={{ config_hash }}
    sha256: 8202b7fde008212d6d36cccf219480f5d54cddb5452b241f47c51cb5c054193b
  - fn: config-updated.sub
    url: http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb={{ config_hash }}
    sha256: 729711e8aa3228db4a3adea9ca5d60de184969a1537ac874477ce5676bee8464

build:
  number: 2003
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - libiconv
    - perl
    - make  # [unix]
    - posix  # [win]
    - m2w64-toolchain  # [win]
    - m2-make  # [win]
    - m2-sed  # [win]
  run:
    - libiconv

test:
  commands:
    - if not exist %LIBRARY_INC%\\popt.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\libpopt.a exit 1  # [win]
    - test -f $PREFIX/include/popt.h  # [unix]
    - test -f $PREFIX/lib/libpopt.a  # [unix]
    - test -f $PREFIX/lib/libpopt.so  # [linux]
    - test -f $PREFIX/lib/libpopt.dylib  # [osx]

about:
  home: http://rpm5.org/
  license: MIT
  license_file: COPYING
  summary: 'Popt is a C library for parsing command line parameters.'

extra:
  recipe-maintainers:
    - notestaff
    - sodre
